from flixnet import Movie, DLLNode, FlixNetLibrary


lib = FlixNetLibrary()
lib.length()
lib.play()
lib.reset()
lib.remove_current()
a1 = Movie('01 Bladerunner 2049', 'Villeneuve', 20171004, False)
a2 = Movie('02 Wonder Woman', 'Jenkins', 20170601, False)
a3 = Movie('03 Mighty', 'Carl', 20170201, False)
a4 = Movie('04 Deaf', 'Rogers', 20161204, False)
a5 = Movie('05 Hail, Caesar!', 'Coen & Coen', 20160304, False)
a6 = Movie('06 The Joker', 'Green', 20151114, False)
a7 = Movie('07 The Imitation Game', 'Tyldum', 20141114, False)
a8 = Movie('08 Belle', 'Garden', 20130114, False)
a9 = Movie('09 Blade', 'Connell', 20121114, False)
a10 = Movie('10 The Stand', 'King', 20120114, False)
lib.add_movie(a6)
print(lib)
lib.get_current()
lib.reset()
print(lib)
lib.remove_current()
print(lib)
lib.play()
lib.search_movie('bla')
lib.reset()
lib.reset()
print(lib)

lib.add_movie(a3)
lib.add_movie(a4)



lib.add_movie(a6)
lib.add_movie(a8)
lib.add_movie(a9)
lib.add_movie(a1)
lib.add_movie(a5)
lib.add_movie(a2)
lib.add_movie(a10)
lib.add_movie(a7)
lib.reset()
print(lib)
lib.search_movie('bla')
print(lib)
'''
lib.reset()
print(lib)
lib.remove_current()
lib.remove_current()
lib.remove_current()
lib.remove_current()
lib.remove_current()
lib.remove_current()
lib.remove_current()
lib.remove_current()
lib.remove_current()
print(lib)
lib.remove_current()
print(lib)
lib.remove_current()
print(lib)
lib.add_movie(a3)
lib.add_movie(a4)
print(lib)
lib.remove_current()
lib.remove_current()
lib.remove_current()
print(lib)
lib.remove_current()
print(lib)
'''
